services:
  app:
    image: my_telegram_chatgpt_bot
    container_name: ps-app
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    # Монтируем сгенерённый файл свойств внутрь контейнера
    volumes:
      - ./application.properties:/config/application.properties:ro
    depends_on:
      - postgresql
    networks:
      - my_network

  postgresql:
    image: postgres:14-alpine
    container_name: my_postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network:

volumes:
  pg_data: