services:
  app:
    image: my_telegram_chatgpt_bot
    container_name: ps-app
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - postgresql
    networks:
      - my_network

networks:
  my_network:
    external: true