services:
  app:
    image: my_telegram_chatgpt_bot
    container_name: ps-app
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - postgresql
    networks:
      - my_network

  postgresql:
    image: postgres:14-alpine
    container_name: my_postgres
    environment:
      - POSTGRES_DB=my_database
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_password
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - my_network

networks:
  my_network:

volumes:
  pg_data: